### ISSUE TITLE
Unable to view unicode character of emotes

### ISSUE THREAD

**Issue by cricketear** [rossengeorgiev/dota2_notebooks#3]
hello, i was looking at the emote table to find the unicode character for :puckchamp: , but after looking at the table i dont think it has the unicode character for any of the emotes, just the preview and alias of the emotes. attached is a screenshot of what im able to see. 

![image](https://user-images.githubusercontent.com/78023134/123541634-60da0100-d6fa-11eb-814b-d25028b71a85.png)

**Comment by rossengeorgiev** [comment]
That is correct. I've removed the columns since a long time ago Valve disable being able to paste them in chat. Why do you need the uinicode char?

**Comment by cricketear** [comment]
> That is correct. I've removed the columns since a long time ago Valve disable being able to paste them in chat. Why do you need the uinicode char?

oh i needed it for a bind so i could press a key and type in chat the :puckchamp: emote, but i was able to find the unicode symbol thing for it yesterday so i no longer need it anymore.

**Comment by rossengeorgiev** [comment]
Can you share what your bind command looks like? And are you saying you have to use unicode char instead of `:puckchamp:` for it to work? If that's the case then its worth adding the char column back

**Comment by cricketear** [comment]
> Can you share what your bind command looks like? And are you saying you have to use unicode char instead of `:puckchamp:` for it to work? If that's the case then its worth adding the char column back

ya sure. the line i put into the console for my bind is:

`bind ] "say_team "`

and since i own the :puckchamp: emote from last years battlepass, the unicode char works for showing the :puckchamp: emote in in-game chat. ive gone into lobbies and used the bind and other players say theyre able to see the emote. i also tried using the unicode char of other TI 10 battlepass emotes that i dont own in demo mode and it works on my own chat, but i havent tried using it in public lobbies.
